var ary1 = ["sato","takae","osada","hio","saitoh","sato"];
var ary2 = ["yabuki","aoki","moriyama","yamada"];
console.log(ary1.length);
console.log(Array.isArray(ary1));
console.log((ary1.toString()));
console.log(ary1.indexOf("sato"));
console.log(ary1.lastIndexOf("sato"));
console.log(ary1.concat(ary2));
console.log(ary1.join("/"));
console.log(ary1.slice(1));
console.log(ary1.slice(1,2));
console.log(ary1.splice(1,2,"kakeya","yamaguchi"));
console.log(ary1);
console.log(Array.of(20,40,60));
console.log(ary1.copyWithin(1,3,5));
console.log(ary1);
console.log(ary2.fill("suzuki",1,3));
console.log(ary2);
console.log(ary1.pop());
console.log(ary1);
console.log(ary1.push("kondo"));
console.log(ary1);